baseurl = "https://mariage-corblet-montes.github.io"
metaDataFormat = "yaml"
title = "Mariage de Pauline et Thibaut"
theme = "blist"

DefaultContentLanguage = "fr"
DefaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
        introTitle = "Wedding Organisation Corblet Montes - 29th June 2024"
        introSubtitle = "You will find below more organizational details."
        introPhoto = "/Pauline_et_Thibaut_dans_le_bus.jpg"
        logo = "/optim2d_bokeh.png"
    
    [[languages.en.menu.main]]
        name = "Welcome page"
        url = ""
        weight = 1

  [languages.fr]
    contentDir = "content/fr" #French
    weight = 1
    languageName = "Français"
    [languages.fr.params]
      introTitle = "Organisation Mariage Corblet Montes - 29 Juin 2024"
      introSubtitle = "Vous trouverez plus bas plus de détails concernant l'organisation."
      introPhoto = "/Pauline_et_Thibaut_dans_le_bus.jpg"
      logo = "/optim2d_bokeh.png"

    [[languages.fr.menu.main]]
        name = "Accueil"
        url = ""
        weight = 1

[params]
# Color theme.
#   Choose from `default`, `ocean`, `forest`, `coffee`, `dark`, or `1950s`.
  color_theme = "forest"
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  favicon = "/optim2d_bokeh.png"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-orange-100"

  # The page bundle that is shown on the front page
  frontBundle = "article"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = true

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  # toc = true
  toc = false

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = true
  # hidePageThumbnail = false

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
